apiVersion: v1
kind: Service
metadata:
  name: webapi-service
spec:
  type: NodePort
  ports:
  - port: {{ .Values.webapi.nodePort }}
    targetPort: 7171
    nodePort: {{ .Values.webapi.nodePort }}
    protocol: TCP
  selector:
    app: webapi